### ISSUE TITLE
Put text on rails

### ISSUE THREAD

**Issue by sej7278** [willemcvu/kicad-panelizer#4]
With JLCPCB if you don't want them to put the customerID in silkscreen in some random location you can put the text "JLCJLCJLCJLC" somewhere and they'll put it there, usually under a chip or something not visible:

https://support.jlcpcb.com/article/28-how-to-put-jlc-production-id-at-a-specified-area-on-the-pcb

apparently if they do the panelization for you then they will put the customerID on the rails, but not sure if they'd figure out to do that if you do the panelization with this script - so how about building it into the script? Obviously the user could put whatever string they liked.

Not sure if this is what you mean by "Put logo/text block on panel border" in the TODO list?

**Comment by sej7278** [comment]
Implemented this in https://github.com/sej7278/kicad-panelizer/commit/6a32924111d0343530f779c725cb668267ead0aa, but it also needs hrail/vrail arguments i added in my master so can't do a PR.

[screenshot](https://imgur.com/a/0RmQzdS)

**Comment by willemcvu** [comment]
By "put logo/text block on panel border" I meant this and also board title, company title, company logo etc. Panel ID stuff.

I'm going to be turning that TODO list into issues here so that I can track them better.

**Comment by sej7278** [comment]
ah ok, that's a lot more complex than my version - i just wanted to automatically add the JLCPCB bit to the rails so they don't mess up my silkscreen!
